packages:
  - packages/*
  - examples/*
  - docs
  - benchmark

ignoredBuiltDependencies:
  - core-js
  - esbuild

onlyBuiltDependencies:
  - '@biomejs/biome'
  - simple-git-hooks
  - unrs-resolver
catalog:
  '@angular/core': ^20.2.3
  '@babel/core': ^7.28.3
  '@babel/types': ^7.28.2
  '@estjs/eslint-config': ^2.1.4
  '@maverick-js/signals': ^6.0.0
  '@playwright/test': ^1.55.0
  '@preact/signals-core': ^1.12.1
  '@types/babel__core': ^7.20.5
  '@types/node': ^22.18.0
  '@vitest/coverage-v8': ^3.2.4
  alien-signals: ^2.0.7
  athen: ^0.0.7-beta.3
  babel-plugin-tester: ^12.0.0
  bumpp: ^10.2.3
  chalk: ^5.6.0
  cross-env: ^10.0.0
  csstype: ^3.1.3
  csv-parse: ^6.1.0
  eslint: ^9.34.0
  fast-glob: ^3.3.3
  jsdom: ^26.1.0
  lint-staged: ^16.1.5
  picocolors: ^1.1.1
  pnpm: ^10.15.0
  prettier: ^3.6.2
  rollup: ^4.49.0
  simple-git-hooks: ^2.13.1
  solid-js: ^1.9.9
  standard-changelog: ^7.0.1
  tsup: ^8.5.0
  tsx: ^4.20.5
  turbo: ^2.5.6
  typescript: ^5.9.2
  unplugin: ^2.3.9
  vite: ^7.1.3
  vite-plugin-inspect: ^11.3.3
  vitest: ^3.2.4
  vue: ^3.6.0-alpha.2
  webpack: ^5.101.3
