export {
  noop,
  _toString,
  extend,
  hasChanged,
  coerceArray,
  hasOwn,
  startsWith,
  escape,
  isExclude,
  ExcludeType,
  generateUniqueId,
  isBrowser,
} from './comm';
export {
  isString,
  isObject,
  isArray,
  isMap,
  isSet,
  isWeakMap,
  isWeakSet,
  isFunction,
  isNil,
  isPromise,
  isSymbol,
  isFalsy,
  isPlainObject,
  isPrimitive,
  isHTMLElement,
  isStringNumber,
  StringNumber,
} from './is';
export { camelCase, kebabCase, capitalizeFirstLetter } from './name';
export { warn, info, error } from './console';
